### ISSUE TITLE
What python version?

### ISSUE THREAD

**Issue by shemnon** [blocktrail/blocktrail-sdk-python#4]
what python version does this run on?  It should be in the docs.

I learned the hard way it isn't Python 3.4.  (the fact it doesn't run in the latest version of python is another issue altogether...)

**Comment by rubensayshi** [comment]
it passes all tests on 2.7.  
I'll make sure it runs on 3.4 before the end of the day!

**Comment by shemnon** [comment]
you might need to fork it, some python changes are not backwards compatible.

**Comment by rubensayshi** [comment]
just pushed a change to master adding support for Python 3.3 and 3.4 (3.2 is a pain in the ass because the `future` package which helps a lot in supporting multiple version does not support 3.2).

all tests pass, but I gotta do a manual look through the code and think about the change in py3 that all strings are unicode by default ...

**Comment by rubensayshi** [comment]
@shemnon after the changes I made did you give it a shot on py 3.4?
